[build]
  # No build command needed - this is a static site
  command = ""
  # Publish the public directory where our HTML files are
  publish = "public"

[build.environment]
  # Node version for Netlify Functions
  NODE_VERSION = "18"

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect any requests to missing files to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
