[build]
publish = "public"
functions = "netlify/functions"

[dev]
command = "npm run dev:vite"
port = 8888
targetPort = 5173
publish = "src"
functions = "netlify/functions"
functionsPort = 9999

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
node_bundler = "esbuild"
