[build]
functions = "netlify/functions"
publish = "public"

[dev]
publish = "public"
functions = "netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
node_bundler = "esbuild"
